# Generated by Django 3.1.5 on 2021-02-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0002_auto_20210201_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkinout',
            old_name='user',
            new_name='users',
        ),
    ]
