# Generated by Django 3.1.5 on 2021-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0004_auto_20210202_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkinout',
            old_name='users',
            new_name='user',
        ),
    ]
