# Generated by Django 3.1.5 on 2021-02-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0004_auto_20210202_1250'),
        ('authentication', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
